// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlApmDWtfFofbPcA8sU5TpvyJUaSwS04',
    appId: '1:1077742973549:web:89e64556626efe855b4564',
    messagingSenderId: '1077742973549',
    projectId: 'notesapp-e2fe8',
    authDomain: 'notesapp-e2fe8.firebaseapp.com',
    storageBucket: 'notesapp-e2fe8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYmrLzJyd5UGzEpe9-PCO724UalBV-sg',
    appId: '1:1077742973549:android:e6e9e2fae8c1f20e5b4564',
    messagingSenderId: '1077742973549',
    projectId: 'notesapp-e2fe8',
    storageBucket: 'notesapp-e2fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOLfH0hyOJRSG1lXzvnx-VAtw11p0RJ8',
    appId: '1:1077742973549:ios:f5176c9185c8b75c5b4564',
    messagingSenderId: '1077742973549',
    projectId: 'notesapp-e2fe8',
    storageBucket: 'notesapp-e2fe8.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

}